version: '3.7'

services:

  shorty:
    build: .
    depends_on:
      - shorty-db
      - shorty-redis
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    privileged: true
    working_dir: /usr/local/app
    environment:
      - DB_HOST=shorty-db
      - DB_USERNAME=db
      - DB_PASSWORD=db
      - DB_DATABASE=db
      - REDIS_HOST=shorty-redis

  shorty-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
    volumes:
      - ./data/backup:/backup
      - ./data/primary/postgresdata:/var/lib/postgresql/data

  shorty-redis:
    image: redis:5.0.7-alpine
    volumes:
      - ./data/redis:/data

      